# Generated by Django 5.2 on 2026-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.BigIntegerField(db_index=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['url_id', '-clicked_at'], name='click_url_time_idx')],
            },
        ),
    ]
