# Generated by Django 5.2 on 2026-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='url',
            name='favicon',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='url',
            name='owner_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='urls', to='shortener.tag'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['is_active', 'expires_at'], name='url_active_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['owner_id', '-created_at'], name='url_owner_created_idx'),
        ),
    ]
